In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [ ]:
arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
rand_arr = np.random.rand(3, 3)
print(rand_arr)

[[0.2988881  0.13220058 0.39194386]
 [0.48315741 0.84105178 0.32693113]
 [0.88478167 0.50529744 0.03251646]]


In [ ]:
rand_int = np.random.randint(0, 10, size=(3, 3))
print(rand_int)

[[5 2 3]
 [4 9 8]
 [4 8 5]]


In [ ]:
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [ ]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [ ]:
print(arr.size)

6


In [ ]:
print(arr.ndim)

2


In [ ]:
print(arr.dtype)

int64


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
flat = reshaped.ravel()
print(flat)

[1 2 3 4 5 6]


In [ ]:
transposed = reshaped.transpose()
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.add(arr1, arr2)
print(result)

[5 7 9]


In [ ]:
result = np.multiply(arr1, arr2)
print(result)

[ 4 10 18]


In [ ]:
result = np.exp(arr1)
print(result)

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))

3.0


In [ ]:
print(np.std(arr))

1.4142135623730951


In [ ]:
print(np.sum(arr))

15


In [ ]:
arr = np.array([3, 1, 2])
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3]
